# Site settings
email: "flydancer@rambler.ru"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Karapyziki
description:
url: ""
twitter_username:
default_img:

# Profile settings
name:
profile_img: "/assets/img/k-logo.png"
profile: "Привет, меня зовут Аннета и это мой блог.
          Здесь я пишу о ветре в волосах, душе нараспашку, закатах у моря,
          поменявшем меня, материнстве, любви, добре, вере, о людях, мыслях, воспоминаниях...
          Это просто мысли вслух, просто буквы, сложенные в строчки,
          разложенные по полочкам, - приссоединяйся, поразмышляем вместе."
social:
  vk: "https://vk.com/manneta"
  facebook: "https://www.facebook.com/anneta.tkachenko.9"
  instagram: "https://www.instagram.com/karapyziki/"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
